### ISSUE TITLE
Safari doesn't submit correct values

### ISSUE THREAD

**Issue by lifeiscontent** [brianblakely/nodep-date-input-polyfill#21]
In a form with a GET request, I am seeing the value `09/19/2016` instead of `2016-09-19`

**Comment by brianblakely** [comment]
You may need to create your own form data object by reading the `value` property of the DOM element, then pass that.  I'm supposing that the browser is choosing to use the displayed date text instead of the underlying value (in which case, the library can't do anything about it without your intervention).
