### ISSUE TITLE
Firefox doesn't submit correct value

### ISSUE THREAD

**Issue by vitorbaptista** [brianblakely/nodep-date-input-polyfill#31]
Similar to #21, on Firefox 49.0.2, the value `09/19/2016` is submitted instead of `2016-09-19`. I'm not sure if I got what you meant by the browser submitting the input text instead of the underlying value, but if I inspect the element on Firefox, the underlying value is on the format `09/19/2016` as well (differently than on Chrome without the polyfill, where it's the expected `2016-09-19`).

You can see where it's breaking by going on https://fda.opentrials.net with Firefox and adding the start date/end date filters.

**Comment by brianblakely** [comment]
Did you reference the [usage notes](https://github.com/brianblakely/nodep-date-input-polyfill#usage-notes) to ensure that the value is being used in the way that the polyfill can support?

In my tests on Firefox 52, accessing the value property of the input element produces the expected YYYY-MM-DD string.  Same with the link that you sent (although that may have been modified since).

If you can still reproduce this with an unmodified version of the polyfill, please comment.  Closing for now.
