### ISSUE TITLE
z-index of "date-input-polyfill"

### ISSUE THREAD

**Issue by JoeyLi-1** [brianblakely/nodep-date-input-polyfill#44]
Hi @brianblakely,

First of all, thank you, this is quite useful.

It has a problem that it could be covered by other controls. like this: 
![image](https://cloud.githubusercontent.com/assets/20162464/26094292/f460f51e-3a4b-11e7-9bed-8f57caaf01f7.png)

If change the z-index to 10000, it works fine. What do you think about this issue? 
(Environment: IE11)

Thanks,
Joey

**Comment by brianblakely** [comment]
You can override the CSS yourself. Refer to the README.

**Comment by JoeyLi-1** [comment]
Just thought that might be a common issue, I already override the z-index by myself. Thank you!

**Comment by brianblakely** [comment]
It might be, I don't have any data to suggest either way. My rationale was that the datepicker shouldn't try to render in front of everything by default, because then it might obscure vital content (like emergency alerts, for example). 

The way it is presently, the datepicker will initially be covered up by other things that are deemed to have high visual priority, and the app dev can decide themselves if and when to increase the datepicker's own priority.

**Comment by JoeyLi-1** [comment]
Yes, that makes sense. Add 1 star to this project. :)

**Comment by BennieCopeland** [comment]
@brianblakely It's not in the README that I can see.

**Comment by brianblakely** [comment]
The first bullet https://github.com/brianblakely/nodep-date-input-polyfill#features

**Comment by BennieCopeland** [comment]
Ah, I was expecting something more specifically referencing the `z-index` issue.
