### ISSUE TITLE
Wrong date when clicking date

### ISSUE THREAD

**Issue by TheDude70** [brianblakely/nodep-date-input-polyfill#6]
When I click on a day the input field gets set with the clicked day -1, i.e. click 29, but 28 is entered. Same when clicking the 'Today' button.

When using up and down arrows it does get the correct date.

**Comment by jcgertig** [comment]
This seams fix can you confirm by getting the most recent version

**Comment by jonnywyatt** [comment]
I have version 2.4.6 and this is still happening, the timezone doesn't seem to accounted for by the toISOString call in valueAsDate?

https://github.com/brianblakely/nodep-date-input-polyfill/blob/master/input.js#L29

**Comment by jcgertig** [comment]
hmm can you try my branch `jcgertig/nodep-date-input-polyfill`

**Comment by hrmoller** [comment]
@jcgertig that seems to work is expected.

**Comment by brianblakely** [comment]
@jonnywyatt 

> the timezone doesn't seem to accounted for by the toISOString call in valueAsDate?

This is intentional.  The standard behavior does not account for timezone.  Compare to Chrome's behavior here, which supports the date input natively.

@TheDude70 

I'm not experiencing any issues with wrong dates via clicks.  A live example would help greatly, but I will continue to investigate.

**Comment by brianblakely** [comment]
Still cannot reproduce.  Please file a new issue with an example, if you are still experiencing this.
